"""create financial investments table

Revision ID: 4d65a2cf1a2a
Revises: 6fc7c98ae8fd
Create Date: 2024-10-21 14:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d65a2cf1a2a'
down_revision = '6fc7c98ae8fd'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_investments',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('investment_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('investment_type', sa.String(length=50), nullable=False),
        sa.Column('asset_name', sa.String(length=100), nullable=False),
        sa.Column('ticker_symbol', sa.String(length=20), nullable=True),
        sa.Column('quantity', sa.Numeric(10, 4), nullable=False),
        sa.Column('purchase_price', sa.Numeric(10, 2), nullable=False),
        sa.Column('current_value', sa.Numeric(10, 2), nullable=True),
        sa.Column('brokerage', sa.String(length=100), nullable=True),
        sa.Column('risk_level', sa.String(length=20), nullable=True),
        sa.Column('dividend_yield', sa.Numeric(5, 2), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('investment_id'),
        sa.CheckConstraint("investment_type IN ('stock', 'crypto', 'real_estate', 'equipment', 'other')", name='check_financial_type')
    )
    
    # Create indexes for better performance
    op.create_index('ix_financial_type', 'financial_investments', ['investment_type'])
    op.create_index('ix_financial_asset', 'financial_investments', ['asset_name'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_financial_asset', table_name='financial_investments')
    op.drop_index('ix_financial_type', table_name='financial_investments')
    op.drop_table('financial_investments')
    # ### end Alembic commands ###
