"""create learning investments table

Revision ID: 9ed814eb330e
Revises: f5b54de9c774
Create Date: 2024-10-21 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9ed814eb330e'
down_revision = 'f5b54de9c774'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_investments',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('investment_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('platform', sa.String(length=100), nullable=True),
        sa.Column('course_name', sa.String(length=200), nullable=False),
        sa.Column('instructor', sa.String(length=200), nullable=True),
        sa.Column('skills_learned', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('completion_percentage', sa.Numeric(5, 2), nullable=True),
        sa.Column('certification_url', sa.String(length=500), nullable=True),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('investment_id')
    )
    
    # Create index for skills searching
    op.create_index('ix_learning_skills', 'learning_investments', ['skills_learned'], postgresql_using='gin')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_learning_skills', table_name='learning_investments')
    op.drop_table('learning_investments')
    # ### end Alembic commands ###
