"""create job applications table

Revision ID: f5b54de9c774
Revises: c3e2fb0a771c
Create Date: 2024-10-21 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f5b54de9c774'
down_revision = 'c3e2fb0a771c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_applications',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('investment_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('company_name', sa.String(length=200), nullable=False),
        sa.Column('position', sa.String(length=200), nullable=False),
        sa.Column('job_url', sa.String(length=500), nullable=True),
        sa.Column('salary_range_min', sa.Numeric(10, 2), nullable=True),
        sa.Column('salary_range_max', sa.Numeric(10, 2), nullable=True),
        sa.Column('application_stage', sa.String(length=50), nullable=False),
        sa.Column('outcome', sa.String(length=50), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('investment_id')
    )
    
    # Create indexes for better performance
    op.create_index('ix_job_applications_outcome', 'job_applications', ['outcome'])
    op.create_index('ix_job_applications_company', 'job_applications', ['company_name'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_applications_company', table_name='job_applications')
    op.drop_index('ix_job_applications_outcome', table_name='job_applications')
    op.drop_table('job_applications')
    # ### end Alembic commands ###
